name: data_pipeline
version: '1.0'
config-version: 2

# The profile to use from profiles.yml
profile: data_pipeline

# Define where your models, analyses, tests, seeds, and macros are stored.
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]

# The directory where compiled SQL and manifest files are stored.
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Model configurations
models:
  data_pipeline:
    staging:
      +materialized: view         # Staging models are materialized as views for performance
      +snowflake_warehouse: dbt_wh  # Warehouse to use for staging models
    marts:
      +materialized: table        # Marts models (fact/dim tables) are materialized as tables
      +snowflake_warehouse: dbt_wh
